# settings to run on Render
import os

import dj_database_url

from .base import *  # noqa: F401, F403

# Database from Render's DATABASE_URL
DATABASES = {
    "default": dj_database_url.config(
        conn_max_age=600,
        conn_health_checks=True,
    )
}

# Use SECRET_KEY env var (generated by Render)
SECRET_KEY = os.environ["SECRET_KEY"]

DEBUG = os.environ.get("DEBUG") == "True"

ALLOWED_HOSTS = [
    ".onrender.com",
]

# CORS — allow the frontend service
CORS_ALLOWED_ORIGINS = [
    os.environ.get("CORS_ALLOWED_ORIGIN", "https://foia-coach.onrender.com"),
]

# WhiteNoise for static files
MIDDLEWARE.insert(1, "whitenoise.middleware.WhiteNoiseMiddleware")  # noqa: F405
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}
